version: '3.0'
services:
    backend:
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - .env
        ports:
            - 127.0.0.1:3333:3333
        restart: unless-stopped
